### ISSUE TITLE
Base-Image austauschen

### ISSUE THREAD

**Issue by spixi** [hackdaysspring2017/hackplan#17]
Das Base-Image docker-registry.rewe-digital.com/rewe-go ist nicht außerhalb des REWE-Netzwerkes erreichbar. Eine DNS-Query auf docker-registry.rewe-digital.com liefert einen NameError.Wenn man hackplan als Open-Source-Projekt entwickeln möchte, muss hier das Base-Image gegen ein öffentlich verfügbares Image getauscht werden.

**Comment by Nepooomuk** [comment]
Guter Punkt, @spixi. Fixe ich morgen mittag. Danke :)

**Comment by spixi** [comment]
kein Problem, Grüße aus der Systems (TIEP)

**Comment by Nepooomuk** [comment]
Ich hab das mal gefixt. Grüße aus Mühlheim und bis spätestens beim nächsten Hackathon
